// <auto-generated />
using System;
using ChessReview.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessReview.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChessReviewDbContext))]
    partial class ChessReviewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.Explanation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<short>("Ply")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Ply", "Language")
                        .IsUnique();

                    b.ToTable("Explanations", t =>
                        {
                            t.HasCheckConstraint("CK_Explanations_Language", "[Language] IN ('ru', 'cs', 'en')");
                        });
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.ExplanationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Language")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ExplanationJobs", t =>
                        {
                            t.HasCheckConstraint("CK_ExplanationJobs_Attempts", "[Attempts] >= 0");

                            t.HasCheckConstraint("CK_ExplanationJobs_Language", "[Language] IN ('ru', 'cs', 'en')");

                            t.HasCheckConstraint("CK_ExplanationJobs_Status", "[Status] IN ('Pending', 'Ready', 'Failed')");
                        });
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlackUser")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ExternalGameId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhiteUser")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalGameId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.Install", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Installs");
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestMoveUci")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("EvalAfterCp")
                        .HasColumnType("int");

                    b.Property<int?>("EvalBeforeCp")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<short?>("MateAfter")
                        .HasColumnType("smallint");

                    b.Property<short?>("MateBefore")
                        .HasColumnType("smallint");

                    b.Property<short>("Ply")
                        .HasColumnType("smallint");

                    b.Property<string>("San")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Uci")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Ply")
                        .IsUnique();

                    b.ToTable("Moves", t =>
                        {
                            t.HasCheckConstraint("CK_Moves_Classification", "[Classification] IN ('Best', 'Excellent', 'Good', 'Book', 'Inaccuracy', 'Mistake', 'Miss', 'Blunder')");

                            t.HasCheckConstraint("CK_Moves_EvalAfter", "([EvalAfterCp] IS NULL AND [MateAfter] IS NOT NULL) OR ([EvalAfterCp] IS NOT NULL AND [MateAfter] IS NULL)");

                            t.HasCheckConstraint("CK_Moves_EvalBefore", "([EvalBeforeCp] IS NULL AND [MateBefore] IS NOT NULL) OR ([EvalBeforeCp] IS NOT NULL AND [MateBefore] IS NULL)");

                            t.HasCheckConstraint("CK_Moves_MateBefore", "[MateBefore] <> 0");
                        });
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.UsageDaily", b =>
                {
                    b.Property<Guid>("InstallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("AnalysisCount")
                        .HasColumnType("int");

                    b.Property<int>("ExplanationCount")
                        .HasColumnType("int");

                    b.HasKey("InstallId", "Date");

                    b.ToTable("UsageDaily");
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.Explanation", b =>
                {
                    b.HasOne("ChessReview.Infrastructure.Persistence.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.ExplanationJob", b =>
                {
                    b.HasOne("ChessReview.Infrastructure.Persistence.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.Move", b =>
                {
                    b.HasOne("ChessReview.Infrastructure.Persistence.Game", null)
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.UsageDaily", b =>
                {
                    b.HasOne("ChessReview.Infrastructure.Persistence.Install", null)
                        .WithMany()
                        .HasForeignKey("InstallId")
                        .HasPrincipalKey("InstallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChessReview.Infrastructure.Persistence.Game", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
